---
name: Release Docker image to GitHub ghcr

on:
  push:
    # branches:
    #   - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  # optional: attach a own name like "/my-sub-context-container"
  IMAGE_NAME: ${{ github.repository }}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

jobs:
  push_to_registry:
    name: Push Docker image to GitHub ghcr
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["22.04", "23.04", "24.04", "25.04"]

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.version }}
            type=semver,pattern={{version}}-${{ matrix.version }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.version }}
            type=semver,pattern={{major}}-${{ matrix.version }}
          flavor: |
            latest=${{ matrix.version == '25.04' && 'auto' || 'false' }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.DATE }}
            VERSION_UBUNTU=${{ matrix.version }}
            PYTHON_ARGS=${{ matrix.version > '22.04' && '--break-system-packages' || '' }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
